const UNFOLLOW_FRIENDS = "friends/UNFOLLOW_FRIENDS";
const SET_FRIENDS = "friends/SET_FRIENDS";
const CLEAR_FRIENDS = "friends/CLEAR_FRIENDS";
const COUNT_FRIENDS = "friends/COUNT_FRIENDS";
const SET_CURRENT_PAGE_FRIENDS = "friends/SET_CURRENT_PAGE_FRIENDS";
const TOGGLE_IS_FETCHING_FRIENDS = "friends/TOGGLE_IS_FETCHING_FRIENDS";
const TOGGLE_IS_FOLLOWING_IN_PROGRESS_FRIENDS =
  "friends/TOGGLE_IS_FOLLOWING_IN_PROGRESS_FRIENDS";
const SET_SEARCH_FRIENDS_NAME = "friends/SET_SEARCH_FRIENDS_NAME";
const CLEAR_ALL_FRIENDS_STATE = "friends/CLEAR_ALL_FRIENDS_STATE";

export {
  UNFOLLOW_FRIENDS,
  SET_FRIENDS,
  CLEAR_FRIENDS,
  COUNT_FRIENDS,
  SET_CURRENT_PAGE_FRIENDS,
  TOGGLE_IS_FETCHING_FRIENDS,
  TOGGLE_IS_FOLLOWING_IN_PROGRESS_FRIENDS,
  SET_SEARCH_FRIENDS_NAME,
  CLEAR_ALL_FRIENDS_STATE,
};
