version: '3.8'

services:
  mongo_db:
    image: 'mongo'
    container_name: 'mongo'
    restart: 'always'
    volumes:
    - 'mongo_data:/data/db'
  api:
    image: mhart/alpine-node:12
    container_name: 'server'
    working_dir: /app/server
    command: sh -c "npm install && npm run start"
    environment:
    - DATABASE_URL=mongodb://localhost:27017/social-network
    - COOKIE_SESSION_SECRET=supersecret
    - JWT_SECRET=supersecret
    ports:
    - "5000:5000"
    depends_on:
    - mongo_db
    - web
    volumes:
    - '.:/app'
  web:
    image: mhart/alpine-node:12
    container_name: 'web'
    working_dir: /app
    command: sh -c "npm cache verify && npm install &&  npm run build-prod"
    volumes:
    - '.:/app'
volumes:
  mongo_data:
  .: