const SET_CONVERSATIONS_PROFILES = "dialogs/SET_MESSAGES_PROFILES";
const SET_OWNER_PROFILE = "dialogs/SET_OWNER_PROFILE";
const CLEARE_CONVERSATIONS_PROFILES = "dialogs/CLEARE_MESSAGES_PROFILES";
const SET_CONVERSATIONS = "dialogs/SET_CONVERSATIONS";
const UPDATE_CONVERSATION = "dialogs/UPDATE_CONVERSATION";
const SET_CONVERSATIONS_COUNT = "dialogs/SET_CONVERSATIONS_COUNT";
const SET_CURRENT_PAGE_CONVERSATIONS = "dialogs/SET_CURRENT_PAGE_CONVERSATIONS";
const SET_MESSAGES = "dialogs/SET_MESSAGES";
const SET_MESSAGES_COUNT = "dialogs/SET_MESSAGES_COUNT";
const SET_CURRENT_PAGE_MESSAGES = "dialogs/SET_CURRENT_PAGE_MESSAGES";
const SET_CURRENT_CONVERSATION_PROFILE =
  "dialogs/SET_CURRENT_CONVERSATION_PROFILE";
const SET_NEW_MESSAGE = "dialogs/SET_NEW_MESSAGE";
const CLEAR_CONVERSATIONS = "dialogs/CLEAR_CONVERSATIONS";
const CLEAR_MESSAGES = "dialogs/CLEAR_MESSAGES";
const CLEAR_CURRENT_CONVERASTION_PROFILE =
  "dialogs/CLEAR_CURRENT_CONVERASTION_PROFILE";
const CLEAR_ALL_DIALOGS = "dialogs/CLEAR_ALL";

export {
  SET_CONVERSATIONS_PROFILES,
  SET_OWNER_PROFILE,
  CLEARE_CONVERSATIONS_PROFILES,
  SET_CONVERSATIONS,
  UPDATE_CONVERSATION,
  SET_CONVERSATIONS_COUNT,
  SET_CURRENT_PAGE_CONVERSATIONS,
  SET_MESSAGES,
  SET_MESSAGES_COUNT,
  SET_CURRENT_PAGE_MESSAGES,
  SET_CURRENT_CONVERSATION_PROFILE,
  SET_NEW_MESSAGE,
  CLEAR_CONVERSATIONS,
  CLEAR_MESSAGES,
  CLEAR_CURRENT_CONVERASTION_PROFILE,
  CLEAR_ALL_DIALOGS,
};
