const FOLLOW = "users/FOLLOW";
const UNFOLLOW = "users/UNFOLLOW";
const SET_USERS = "users/SET-USERS";
const CLEAR_USERS = "users/CLEAR_USERS";
const COUNT_USERS = "users/COUNT-USERS";
const SET_CURRENT_PAGE = "users/SET_CURRENT_PAGE";
const TOGGLE_IS_FETCHING = "users/TOGGLE_IS_FETCHING";
const TOGGLE_IS_FOLLOWING_IN_PROGRESS = "users/TOGGLE_IS_FOLLOWING_IN_PROGRESS";
const SET_SEARCH_USER_NAME = "users/SET_SEATCH_USER_NAME";
const CLEAR_ALL_USERS_STATE = "users/CLEAR_ALL_USERS_STATE";

export {
  FOLLOW,
  UNFOLLOW,
  SET_USERS,
  CLEAR_USERS,
  COUNT_USERS,
  SET_CURRENT_PAGE,
  TOGGLE_IS_FETCHING,
  TOGGLE_IS_FOLLOWING_IN_PROGRESS,
  SET_SEARCH_USER_NAME,
  CLEAR_ALL_USERS_STATE,
};
