const AUTH_SET_USER_DATA = "auth/AUTH_SET_USER_DATA";
const AUTH_LOGIN = "auth/AUTH_LOGIN";
const AUTH_SET_USER = "auth/AUTH_SET_USER";
const AUTH_SET_UNREAD_CONVERSATIONS = "auth/AUTH_SET_UNREAD_CONVERSATIONS";

export {
  AUTH_SET_USER_DATA,
  AUTH_LOGIN,
  AUTH_SET_USER,
  AUTH_SET_UNREAD_CONVERSATIONS,
};
