const AUTH_SET_USER_DATA = "auth/AUTH_SET_USER_DATA";
const AUTH_LOGIN = "auth/AUTH_LOGIN";
const AUTH_SET_USER = "auth/AUTH_SET_USER";
const AUTH_SET_UNREAD_CONVERSATIONS = "auth/AUTH_SET_UNREAD_CONVERSATIONS";
const AUTH_CLEAR_REG_URL = "auth/AUTH_CLEAR_REG_URL";
const AUTH_UPDATE_REG_URL = "auth/AUTH_UPDATE_REG_URL";

export {
  AUTH_SET_USER_DATA,
  AUTH_LOGIN,
  AUTH_SET_USER,
  AUTH_SET_UNREAD_CONVERSATIONS,
  AUTH_CLEAR_REG_URL,
  AUTH_UPDATE_REG_URL,
};
