const SET_USER_PROFILE = "profile/SET_USER_PROFILE";
const SET_STATUS = "profile/SET_STATUS";
const SAVE_PHOTO_SUCCESS = "profile/SAVE_PHOTO_SUCCESS";
const SET_RANDOM_FRIENDS = "profile/SET_RANDOM_FRIENDS";
const SET_WALL_POSTS = "profile/SET_WALL_POSTS";
const COUNT_WALL_POSTS = "profile/COUNT_WALL_POSTS";
const SET_CURRENT_PAGE_WALL = "profile/SET_CURRENT_PAGE_WALL";
const CLEARE_WALL_POSTS = "profile/CLEARE_WALL_POSTS";
const CLEARE_PROFILE = "profile/CLEARE_PROFILE";
const SET_NEW_POST = "profile/SET_NEW_POST";
const COUNT_PROFILE_PHOTOS = "profile/COUNT_PROFILE_PHOTOS";
const SET_CURRENT_PAGE_PHOTOS = "profile/SET_CURRENT_PAGE_PHOTOS";
const CLEARE_PAGE_PHOTOS = "profile/CLEARE_PAGE_PHOTOS";
const SET_PROFILE_PHOTOS = "profile/SET_PROFILE_PHOTOS";
const SET_NEW_PHOTOS = "profile/SET_NEW_PHOTOS";

export {
  SET_USER_PROFILE,
  SET_STATUS,
  SAVE_PHOTO_SUCCESS,
  SET_RANDOM_FRIENDS,
  SET_WALL_POSTS,
  COUNT_WALL_POSTS,
  SET_CURRENT_PAGE_WALL,
  CLEARE_WALL_POSTS,
  CLEARE_PROFILE,
  SET_NEW_POST,
  COUNT_PROFILE_PHOTOS,
  SET_CURRENT_PAGE_PHOTOS,
  CLEARE_PAGE_PHOTOS,
  SET_PROFILE_PHOTOS,
  SET_NEW_PHOTOS,
};
