const SET_PROFILE = "news/SET_PROFILE";
const SET_NEWS_PROFILES = "news/SET_NEWS_PROFILES";
const SET_NEWS = "news/SET_NEWS";
const SET_CURRENT_PAGE_NEWS = "news/SET_CURRENT_PAGE_NEWS";
const COUNT_NEWS = "news/COUNT_NEWS";
const CLEARE_NEWS_ITEMS = "news/CLEARE_NEWS_ITEMS";
const CLEARE_NEWS_PROFILES = "news/CLEARE_NEWS_PROFILES";

export {
  SET_PROFILE,
  SET_NEWS_PROFILES,
  SET_NEWS,
  SET_CURRENT_PAGE_NEWS,
  COUNT_NEWS,
  CLEARE_NEWS_ITEMS,
  CLEARE_NEWS_PROFILES,
};
